# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/liy0h/exageostatR/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/liy0h/exageostatR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liy0h/exageostatR/CMakeFiles /Users/liy0h/exageostatR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liy0h/exageostatR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exageostat

# Build rule for target.
exageostat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exageostat
.PHONY : exageostat

# fast build rule for target.
exageostat/fast:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/build
.PHONY : exageostat/fast

exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.o: exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.o

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.o

# target to build an object file
exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.o
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.o

exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.i: exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.i

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.i

# target to preprocess a source file
exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.i
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.i

exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.s: exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.s

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.s

# target to generate assembly for a file
exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.s
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.c.s

exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.o: exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.o

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.o

# target to build an object file
exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.o
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.o

exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.i: exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.i

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.i

# target to preprocess a source file
exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.i
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.i

exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.s: exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.s

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.s

# target to generate assembly for a file
exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.s
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.c.s

exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.o: exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.o

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.o

# target to build an object file
exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.o
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.o

exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.i: exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.i

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.i

# target to preprocess a source file
exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.i
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.i

exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.s: exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.s

.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.s

# target to generate assembly for a file
exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.s
.PHONY : exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.c.s

exageostat_approx/src/compute/MLE_approx.o: exageostat_approx/src/compute/MLE_approx.c.o

.PHONY : exageostat_approx/src/compute/MLE_approx.o

# target to build an object file
exageostat_approx/src/compute/MLE_approx.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_approx.c.o
.PHONY : exageostat_approx/src/compute/MLE_approx.c.o

exageostat_approx/src/compute/MLE_approx.i: exageostat_approx/src/compute/MLE_approx.c.i

.PHONY : exageostat_approx/src/compute/MLE_approx.i

# target to preprocess a source file
exageostat_approx/src/compute/MLE_approx.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_approx.c.i
.PHONY : exageostat_approx/src/compute/MLE_approx.c.i

exageostat_approx/src/compute/MLE_approx.s: exageostat_approx/src/compute/MLE_approx.c.s

.PHONY : exageostat_approx/src/compute/MLE_approx.s

# target to generate assembly for a file
exageostat_approx/src/compute/MLE_approx.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_approx.c.s
.PHONY : exageostat_approx/src/compute/MLE_approx.c.s

exageostat_approx/src/compute/MLE_lr.o: exageostat_approx/src/compute/MLE_lr.c.o

.PHONY : exageostat_approx/src/compute/MLE_lr.o

# target to build an object file
exageostat_approx/src/compute/MLE_lr.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_lr.c.o
.PHONY : exageostat_approx/src/compute/MLE_lr.c.o

exageostat_approx/src/compute/MLE_lr.i: exageostat_approx/src/compute/MLE_lr.c.i

.PHONY : exageostat_approx/src/compute/MLE_lr.i

# target to preprocess a source file
exageostat_approx/src/compute/MLE_lr.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_lr.c.i
.PHONY : exageostat_approx/src/compute/MLE_lr.c.i

exageostat_approx/src/compute/MLE_lr.s: exageostat_approx/src/compute/MLE_lr.c.s

.PHONY : exageostat_approx/src/compute/MLE_lr.s

# target to generate assembly for a file
exageostat_approx/src/compute/MLE_lr.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/MLE_lr.c.s
.PHONY : exageostat_approx/src/compute/MLE_lr.c.s

exageostat_approx/src/compute/dpotrf_diag.o: exageostat_approx/src/compute/dpotrf_diag.c.o

.PHONY : exageostat_approx/src/compute/dpotrf_diag.o

# target to build an object file
exageostat_approx/src/compute/dpotrf_diag.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/dpotrf_diag.c.o
.PHONY : exageostat_approx/src/compute/dpotrf_diag.c.o

exageostat_approx/src/compute/dpotrf_diag.i: exageostat_approx/src/compute/dpotrf_diag.c.i

.PHONY : exageostat_approx/src/compute/dpotrf_diag.i

# target to preprocess a source file
exageostat_approx/src/compute/dpotrf_diag.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/dpotrf_diag.c.i
.PHONY : exageostat_approx/src/compute/dpotrf_diag.c.i

exageostat_approx/src/compute/dpotrf_diag.s: exageostat_approx/src/compute/dpotrf_diag.c.s

.PHONY : exageostat_approx/src/compute/dpotrf_diag.s

# target to generate assembly for a file
exageostat_approx/src/compute/dpotrf_diag.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/dpotrf_diag.c.s
.PHONY : exageostat_approx/src/compute/dpotrf_diag.c.s

exageostat_approx/src/compute/pdpotrf_diag.o: exageostat_approx/src/compute/pdpotrf_diag.c.o

.PHONY : exageostat_approx/src/compute/pdpotrf_diag.o

# target to build an object file
exageostat_approx/src/compute/pdpotrf_diag.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/pdpotrf_diag.c.o
.PHONY : exageostat_approx/src/compute/pdpotrf_diag.c.o

exageostat_approx/src/compute/pdpotrf_diag.i: exageostat_approx/src/compute/pdpotrf_diag.c.i

.PHONY : exageostat_approx/src/compute/pdpotrf_diag.i

# target to preprocess a source file
exageostat_approx/src/compute/pdpotrf_diag.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/pdpotrf_diag.c.i
.PHONY : exageostat_approx/src/compute/pdpotrf_diag.c.i

exageostat_approx/src/compute/pdpotrf_diag.s: exageostat_approx/src/compute/pdpotrf_diag.c.s

.PHONY : exageostat_approx/src/compute/pdpotrf_diag.s

# target to generate assembly for a file
exageostat_approx/src/compute/pdpotrf_diag.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_approx/src/compute/pdpotrf_diag.c.s
.PHONY : exageostat_approx/src/compute/pdpotrf_diag.c.s

exageostat_exact/core/compute/core_dcmg.o: exageostat_exact/core/compute/core_dcmg.c.o

.PHONY : exageostat_exact/core/compute/core_dcmg.o

# target to build an object file
exageostat_exact/core/compute/core_dcmg.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dcmg.c.o
.PHONY : exageostat_exact/core/compute/core_dcmg.c.o

exageostat_exact/core/compute/core_dcmg.i: exageostat_exact/core/compute/core_dcmg.c.i

.PHONY : exageostat_exact/core/compute/core_dcmg.i

# target to preprocess a source file
exageostat_exact/core/compute/core_dcmg.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dcmg.c.i
.PHONY : exageostat_exact/core/compute/core_dcmg.c.i

exageostat_exact/core/compute/core_dcmg.s: exageostat_exact/core/compute/core_dcmg.c.s

.PHONY : exageostat_exact/core/compute/core_dcmg.s

# target to generate assembly for a file
exageostat_exact/core/compute/core_dcmg.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dcmg.c.s
.PHONY : exageostat_exact/core/compute/core_dcmg.c.s

exageostat_exact/core/compute/core_ddotp.o: exageostat_exact/core/compute/core_ddotp.c.o

.PHONY : exageostat_exact/core/compute/core_ddotp.o

# target to build an object file
exageostat_exact/core/compute/core_ddotp.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_ddotp.c.o
.PHONY : exageostat_exact/core/compute/core_ddotp.c.o

exageostat_exact/core/compute/core_ddotp.i: exageostat_exact/core/compute/core_ddotp.c.i

.PHONY : exageostat_exact/core/compute/core_ddotp.i

# target to preprocess a source file
exageostat_exact/core/compute/core_ddotp.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_ddotp.c.i
.PHONY : exageostat_exact/core/compute/core_ddotp.c.i

exageostat_exact/core/compute/core_ddotp.s: exageostat_exact/core/compute/core_ddotp.c.s

.PHONY : exageostat_exact/core/compute/core_ddotp.s

# target to generate assembly for a file
exageostat_exact/core/compute/core_ddotp.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_ddotp.c.s
.PHONY : exageostat_exact/core/compute/core_ddotp.c.s

exageostat_exact/core/compute/core_dmdet.o: exageostat_exact/core/compute/core_dmdet.c.o

.PHONY : exageostat_exact/core/compute/core_dmdet.o

# target to build an object file
exageostat_exact/core/compute/core_dmdet.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dmdet.c.o
.PHONY : exageostat_exact/core/compute/core_dmdet.c.o

exageostat_exact/core/compute/core_dmdet.i: exageostat_exact/core/compute/core_dmdet.c.i

.PHONY : exageostat_exact/core/compute/core_dmdet.i

# target to preprocess a source file
exageostat_exact/core/compute/core_dmdet.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dmdet.c.i
.PHONY : exageostat_exact/core/compute/core_dmdet.c.i

exageostat_exact/core/compute/core_dmdet.s: exageostat_exact/core/compute/core_dmdet.c.s

.PHONY : exageostat_exact/core/compute/core_dmdet.s

# target to generate assembly for a file
exageostat_exact/core/compute/core_dmdet.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dmdet.c.s
.PHONY : exageostat_exact/core/compute/core_dmdet.c.s

exageostat_exact/core/compute/core_dzcpy.o: exageostat_exact/core/compute/core_dzcpy.c.o

.PHONY : exageostat_exact/core/compute/core_dzcpy.o

# target to build an object file
exageostat_exact/core/compute/core_dzcpy.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dzcpy.c.o
.PHONY : exageostat_exact/core/compute/core_dzcpy.c.o

exageostat_exact/core/compute/core_dzcpy.i: exageostat_exact/core/compute/core_dzcpy.c.i

.PHONY : exageostat_exact/core/compute/core_dzcpy.i

# target to preprocess a source file
exageostat_exact/core/compute/core_dzcpy.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dzcpy.c.i
.PHONY : exageostat_exact/core/compute/core_dzcpy.c.i

exageostat_exact/core/compute/core_dzcpy.s: exageostat_exact/core/compute/core_dzcpy.c.s

.PHONY : exageostat_exact/core/compute/core_dzcpy.s

# target to generate assembly for a file
exageostat_exact/core/compute/core_dzcpy.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/core/compute/core_dzcpy.c.s
.PHONY : exageostat_exact/core/compute/core_dzcpy.c.s

exageostat_exact/runtime/starpu/codelets/codelet_dcmg.o: exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.o

exageostat_exact/runtime/starpu/codelets/codelet_dcmg.i: exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.i

exageostat_exact/runtime/starpu/codelets/codelet_dcmg.s: exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dcmg.c.s

exageostat_exact/runtime/starpu/codelets/codelet_ddotp.o: exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.o

exageostat_exact/runtime/starpu/codelets/codelet_ddotp.i: exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.i

exageostat_exact/runtime/starpu/codelets/codelet_ddotp.s: exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_ddotp.c.s

exageostat_exact/runtime/starpu/codelets/codelet_dgemv.o: exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.o

exageostat_exact/runtime/starpu/codelets/codelet_dgemv.i: exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.i

exageostat_exact/runtime/starpu/codelets/codelet_dgemv.s: exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dgemv.c.s

exageostat_exact/runtime/starpu/codelets/codelet_dmdet.o: exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.o

exageostat_exact/runtime/starpu/codelets/codelet_dmdet.i: exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.i

exageostat_exact/runtime/starpu/codelets/codelet_dmdet.s: exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmdet.c.s

exageostat_exact/runtime/starpu/codelets/codelet_dmse.o: exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.o

exageostat_exact/runtime/starpu/codelets/codelet_dmse.i: exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.i

exageostat_exact/runtime/starpu/codelets/codelet_dmse.s: exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dmse.c.s

exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.o: exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.o

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.o

# target to build an object file
exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.o
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.o

exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.i: exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.i

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.i

# target to preprocess a source file
exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.i
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.i

exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.s: exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.s

.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.s

# target to generate assembly for a file
exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.s
.PHONY : exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.c.s

exageostat_exact/src/compute/MLE_exact.o: exageostat_exact/src/compute/MLE_exact.c.o

.PHONY : exageostat_exact/src/compute/MLE_exact.o

# target to build an object file
exageostat_exact/src/compute/MLE_exact.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/src/compute/MLE_exact.c.o
.PHONY : exageostat_exact/src/compute/MLE_exact.c.o

exageostat_exact/src/compute/MLE_exact.i: exageostat_exact/src/compute/MLE_exact.c.i

.PHONY : exageostat_exact/src/compute/MLE_exact.i

# target to preprocess a source file
exageostat_exact/src/compute/MLE_exact.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/src/compute/MLE_exact.c.i
.PHONY : exageostat_exact/src/compute/MLE_exact.c.i

exageostat_exact/src/compute/MLE_exact.s: exageostat_exact/src/compute/MLE_exact.c.s

.PHONY : exageostat_exact/src/compute/MLE_exact.s

# target to generate assembly for a file
exageostat_exact/src/compute/MLE_exact.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/exageostat_exact/src/compute/MLE_exact.c.s
.PHONY : exageostat_exact/src/compute/MLE_exact.c.s

misc/compute/MLE_misc.o: misc/compute/MLE_misc.c.o

.PHONY : misc/compute/MLE_misc.o

# target to build an object file
misc/compute/MLE_misc.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/MLE_misc.c.o
.PHONY : misc/compute/MLE_misc.c.o

misc/compute/MLE_misc.i: misc/compute/MLE_misc.c.i

.PHONY : misc/compute/MLE_misc.i

# target to preprocess a source file
misc/compute/MLE_misc.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/MLE_misc.c.i
.PHONY : misc/compute/MLE_misc.c.i

misc/compute/MLE_misc.s: misc/compute/MLE_misc.c.s

.PHONY : misc/compute/MLE_misc.s

# target to generate assembly for a file
misc/compute/MLE_misc.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/MLE_misc.c.s
.PHONY : misc/compute/MLE_misc.c.s

misc/compute/flat_file.o: misc/compute/flat_file.c.o

.PHONY : misc/compute/flat_file.o

# target to build an object file
misc/compute/flat_file.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/flat_file.c.o
.PHONY : misc/compute/flat_file.c.o

misc/compute/flat_file.i: misc/compute/flat_file.c.i

.PHONY : misc/compute/flat_file.i

# target to preprocess a source file
misc/compute/flat_file.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/flat_file.c.i
.PHONY : misc/compute/flat_file.c.i

misc/compute/flat_file.s: misc/compute/flat_file.c.s

.PHONY : misc/compute/flat_file.s

# target to generate assembly for a file
misc/compute/flat_file.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/misc/compute/flat_file.c.s
.PHONY : misc/compute/flat_file.c.s

r-wrappers/compute/rwrappers.o: r-wrappers/compute/rwrappers.c.o

.PHONY : r-wrappers/compute/rwrappers.o

# target to build an object file
r-wrappers/compute/rwrappers.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/r-wrappers/compute/rwrappers.c.o
.PHONY : r-wrappers/compute/rwrappers.c.o

r-wrappers/compute/rwrappers.i: r-wrappers/compute/rwrappers.c.i

.PHONY : r-wrappers/compute/rwrappers.i

# target to preprocess a source file
r-wrappers/compute/rwrappers.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/r-wrappers/compute/rwrappers.c.i
.PHONY : r-wrappers/compute/rwrappers.c.i

r-wrappers/compute/rwrappers.s: r-wrappers/compute/rwrappers.c.s

.PHONY : r-wrappers/compute/rwrappers.s

# target to generate assembly for a file
r-wrappers/compute/rwrappers.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/r-wrappers/compute/rwrappers.c.s
.PHONY : r-wrappers/compute/rwrappers.c.s

src/compute/MLE.o: src/compute/MLE.c.o

.PHONY : src/compute/MLE.o

# target to build an object file
src/compute/MLE.c.o:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/src/compute/MLE.c.o
.PHONY : src/compute/MLE.c.o

src/compute/MLE.i: src/compute/MLE.c.i

.PHONY : src/compute/MLE.i

# target to preprocess a source file
src/compute/MLE.c.i:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/src/compute/MLE.c.i
.PHONY : src/compute/MLE.c.i

src/compute/MLE.s: src/compute/MLE.c.s

.PHONY : src/compute/MLE.s

# target to generate assembly for a file
src/compute/MLE.c.s:
	$(MAKE) -f CMakeFiles/exageostat.dir/build.make CMakeFiles/exageostat.dir/src/compute/MLE.c.s
.PHONY : src/compute/MLE.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... exageostat"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.o"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.i"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dcmg_diag.s"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.o"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.i"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_dpotrf_diag.s"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.o"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.i"
	@echo "... exageostat_approx/runtime/starpu/codelets/codelet_hicma_dmdet.s"
	@echo "... exageostat_approx/src/compute/MLE_approx.o"
	@echo "... exageostat_approx/src/compute/MLE_approx.i"
	@echo "... exageostat_approx/src/compute/MLE_approx.s"
	@echo "... exageostat_approx/src/compute/MLE_lr.o"
	@echo "... exageostat_approx/src/compute/MLE_lr.i"
	@echo "... exageostat_approx/src/compute/MLE_lr.s"
	@echo "... exageostat_approx/src/compute/dpotrf_diag.o"
	@echo "... exageostat_approx/src/compute/dpotrf_diag.i"
	@echo "... exageostat_approx/src/compute/dpotrf_diag.s"
	@echo "... exageostat_approx/src/compute/pdpotrf_diag.o"
	@echo "... exageostat_approx/src/compute/pdpotrf_diag.i"
	@echo "... exageostat_approx/src/compute/pdpotrf_diag.s"
	@echo "... exageostat_exact/core/compute/core_dcmg.o"
	@echo "... exageostat_exact/core/compute/core_dcmg.i"
	@echo "... exageostat_exact/core/compute/core_dcmg.s"
	@echo "... exageostat_exact/core/compute/core_ddotp.o"
	@echo "... exageostat_exact/core/compute/core_ddotp.i"
	@echo "... exageostat_exact/core/compute/core_ddotp.s"
	@echo "... exageostat_exact/core/compute/core_dmdet.o"
	@echo "... exageostat_exact/core/compute/core_dmdet.i"
	@echo "... exageostat_exact/core/compute/core_dmdet.s"
	@echo "... exageostat_exact/core/compute/core_dzcpy.o"
	@echo "... exageostat_exact/core/compute/core_dzcpy.i"
	@echo "... exageostat_exact/core/compute/core_dzcpy.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dcmg.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dcmg.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dcmg.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_ddotp.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_ddotp.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_ddotp.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dgemv.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dgemv.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dgemv.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmdet.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmdet.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmdet.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmse.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmse.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dmse.s"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.o"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.i"
	@echo "... exageostat_exact/runtime/starpu/codelets/codelet_dzcpy.s"
	@echo "... exageostat_exact/src/compute/MLE_exact.o"
	@echo "... exageostat_exact/src/compute/MLE_exact.i"
	@echo "... exageostat_exact/src/compute/MLE_exact.s"
	@echo "... misc/compute/MLE_misc.o"
	@echo "... misc/compute/MLE_misc.i"
	@echo "... misc/compute/MLE_misc.s"
	@echo "... misc/compute/flat_file.o"
	@echo "... misc/compute/flat_file.i"
	@echo "... misc/compute/flat_file.s"
	@echo "... r-wrappers/compute/rwrappers.o"
	@echo "... r-wrappers/compute/rwrappers.i"
	@echo "... r-wrappers/compute/rwrappers.s"
	@echo "... src/compute/MLE.o"
	@echo "... src/compute/MLE.i"
	@echo "... src/compute/MLE.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

